version: '3.8'
services:
  musicmonitor:
    build: .
    container_name: musicmonitor
    restart: unless-stopped
    volumes:
      - /mnt/nas/Music:/mnt/nas/Music
      - ./config.yaml:/root/.config/beets/config.yaml
      - /data/MusicMonitor/library.db:/app/library.db
    command: ["python", "-u", "music_monitor.py"]
